#!/usr/bin/env bash
# Install nginx web server.
sudo apt update
sudo apt install nginx -y
ufw allow 'Nginx HTTP'
sudo vi /var/www/html/index.nginx-debian.html
Holberton School
sudo service nginx start
