#!/usr/bin/env bash
# Install nginx web server.
sudo apt-get update && sudo apt-get install nginx
sudo ufw allow 'Nginx HTTP'
sudo echo "Holberton School" | sudo tee /var/www/html/index.html > /dev/null
sudo service nginx start
