#!/usr/bin/env bash
# Install nginx web server.
sudo apt-get update
sudo apt-get install -y nginx
ufw allow 'Nginx HTTP'
echo "Holberton School" > /var/www/html/index.nginx-debian.html
sudo service nginx start
